name: Manual workflow

on:
  push:
    branches:
    - main
    
env:
  MY_NAME: igor
    
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "Hello $MY_NAME"
