name: Manual workflow

on:
  push:
    branches:
    - main
env:
  nome: Juvenal
  
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Send greeting
        run: echo "$nome"
  
      
