name: Manual workflow

on:
  push:
    branches:
    - master
    
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: echo "${{toJSON(github.event.commits[0])}}"
