name: CI

on:
  push:
    branches: [ master ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 17.x
          
      - name: Install Dependencies
        run: yarn
        
      - name: Install Dependencies
        run: console.log('teste')
