name: Manual workflow

on:
  push:
    branches:
    - main
env:
  commitMessage: ${{ github.event.head_commit.message }}
  
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Split commit message
        run: $commitMessageSplit = $commitMessage.split('-')
      - name: print
        run: echo "$commitMessageSplit"
  
      
