name: Manual workflow

on:
  push:
    branches:
    - main
env:
  commitMessage: ${{ github.event.head_commit.message }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
            node-version: 17.x
      - name: Instalar dependencias
        run: yarn 
      - name: Verificar se existe comando
        run: console.log('existe')
  
      
