name: Manual workflow

on:
  push:
    branches:
    - main
    
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Verificar commit
      run: echo '${{github.event.head_commit.message}}'
      
    - name: Separar commit
      run: IFS='n/' read -a array <<< "${{github.event.head_commit.message}}"; echo "${array[1]}"
